---
title: "RealDataMAP"
author: "Emil Myhre"
date: "29 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r MAP}
library(RcppCNPy)
library(EnvStats)
ApSim = npyLoad("ApEstData19113Ind11v6Sim.npy")
TauSim = npyLoad("TauEstData19113Ind11v6Sim.npy")
ApAlt = npyLoad("ApEstData19113Ind11v6.npy")
TauAlt = npyLoad("TauEstData19113Ind11v6.npy")
stepsize <- 0.00001
dens <- function(x,Data=Data1_1){
  return (demp(x,Data))
}
x <- seq(from = 0, to = 0.01, by = stepsize)

MapApSim = which.max(unlist(lapply(x, FUN = dens, ApSim[c(500:1200)])) - 1)*stepsize
MapTauSim =  which.max(unlist(lapply(x, FUN = dens, TauSim)) - 1)*stepsize
MapApAlt =  which.max(unlist(lapply(x, FUN = dens, ApAlt[c(500:1200)])) - 1)*stepsize
MapTauAlt =  which.max(unlist(lapply(x, FUN = dens, TauAlt)) - 1)*stepsize
npySave("MapApData19113Ind11v6Sim.npy",MapApSim)
npySave("MapTauData19113Ind11v6Sim.npy",MapTauSim)
npySave("MapApData19113Ind11v6.npy",MapApAlt)
npySave("MapTauData19113Ind11v6.npy",MapTauAlt)
```

